# /summit/Cargo.toml
[workspace]
members = [
    "crates/summitd",
    "crates/summit-core",
    "crates/summit-services",
    "crates/summit-api",
    "crates/libsummit",
    "crates/summit-ctl",
    "tests/integration",
]
resolver = "2"
